### PR TITLE
Add talk schedule

### PR DESCRIPTION
**Pull request by kirang89**

### CODE REVIEW

**Comment by kirang89** [comment]
@kracekumar: Kindly do the review :)

I'm not sure where the talks by goibibo and redhat should be placed, now that the timings have changed. Let me know if further changes are required.

**Comment by kracekumar** [comment]
@kirang89 We need to link to original session as well. For sponsored session we can do that later.You can create a separate row and do it for redhat. GoIbibo it is at 2.00 PM.

**Comment by kirang89** [comment]
- What's the timeslot for redhat ?
- On which day is the goibibo session ?

**Comment by kracekumar** [comment]
RedHat - Oct 4, 12:30 - 1:00
GoIbibo - Oct 3, 2:00 - 2:45

**Comment by kirang89** [comment]
- Redhat's proposal replaces Microsoft's. So, where does Microsoft's proposal go to ?
  These are the slots for 12:15 PM:
  - How to build microservices using ZeroMQ and WSGI, Room 01
  - Building flexible filesystems with FUSE-Python, Room 02
  - Build Python Web Apps in a breeze with Visual Studio (Microsoft), Room 03 
- The 02.00 PM slot is allocated as follows:
  - Lightning Talk, Room 01
  - Lightning Talk, Room 02
  - Building Offensive Web Security Framework in Python (non-sponsor talk), Room 03
  
  Which room do I allocate for goibibo ?

**Comment by kracekumar** [comment]
I have updated the sheet with all modified details. Can you refer that ?

**Comment by kirang89** [comment]
Updated with changes :+1:

**Comment by kracekumar** [comment]
I will merge and see how it looks on actual site. If any changes needed will add here.

**Comment by kracekumar** [comment]
For sponsored session, we need to have `Sponsored - Revolutionizing e-commerce using hyper-local way`.

**Comment by kirang89** [comment]
Let me know once you're done checking for changes.

**Comment by kracekumar** [comment]
Good Idiom.

**Pull request merged**
