### PR TITLE
Add workshop schedule

### LINKED ISSUE #14: Add workshop schedule to website
List of confirmed workshops on oct 2. We need to add this to schedule page

```
9:00 - 12:30 - Let's Learn Statistics - Room 1
9.00 - 12:30 - Django Projects the Right way! - Room 2
9.00 - 12:30 - Getting Started with Ansible - Room 3
1:00 - 3:30 - Reasoning under uncertainty with Python
1:00 - 3:30 - Symbolic computation with Python SymPy
1:00 - 3:30 - Using devstack to contribute to OpenStack
4:00 - 6:30 - Thinking in Functions
4:00 - 6:30 - Building NextGen IoT solutions using Python and Cloud
4:00 - 6:30 - Python on your Mobile Phone(advanced concepts)
```

Also link to appropriate proposal page.

### PR DESCRIPTION
**Pull request by kirang89**
This resolves #14.

### CODE REVIEW

**Comment by kracekumar** [comment]
Just two changes required.
- We need to replace `Auditorium` with `Room`, so it becomes `Room 1`, `Room 2`, `Room 3`.
- Add a simple button to buy ticket for each workshop which takes to `https://in.explara.com/e/pycon-india-2015/checkout` in a new tab.

**Comment by kirang89** [comment]
I'll get on it right away.

**Comment by kirang89** [comment]
@kracekumar Take a look.

**Comment by kracekumar** [comment]
@kirang89 :+1:

**Pull request merged**
