### PR TITLE
Add and use square version of every panel members for better visibility

### PR DESCRIPTION
**Pull request by theskumar**
200px@2x = 400px is used for retina displays.

### CODE REVIEW

**Comment by kracekumar** [comment]
Can we disable anime ?

**Comment by theskumar** [comment]
Yeah sure. I was not sure, why that color rotation thing was happening at first place.

**Comment by kracekumar** [comment]
I think it is because of class  `introanime`.

**Comment by theskumar** [comment]
checking. will create a new pr.

**Comment by theskumar** [comment]
Here we go: https://github.com/pythonindia/inpycon2015/pull/28

**Pull request merged**
