### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by shankisg**
Before going ahead with merge, do the folllowing below

1 Checkout the branch assigned for merge.

2 Install requirements in virtual env.

3 Go inside project root directory and run "fab build"

4 Go inside output folder and run  "python -m SimpleHTTPServer"

5  Go to browser and access http://localhost:8000 and http://localhost:8000/blog

6  If you want to add a blog post, go to content/blog folder and add your-file.md  file.  Then follow step 4 and step 5.

More information on how to work/structure, I will be putting in comments below

### CODE REVIEW

**Comment by shankisg** [comment]
I am maintaining 2 separate themes, one for frontend site(theme/site) and other for blog (theme/blog).
- To modify templates related for frontend site such as index.html, sponsorship.html etc. The modifications needs to be done on theme/site/templates.

templates/
|-- base.html
|-- blogs.html
|-- disqus.html
|-- faq.html
|-- footer.html
|-- header.html
|-- home.html
|-- index.html
|-- post.html
|-- speakers.html
|-- sponsorship.html
|-- sponsors.html
`-- venue.html
- To modify templates related for blog site such as index.html etc. The modifications needs to be done on theme/blog/templates.

templates/
|-- analytics.html
|-- archives.html
|-- article.html
|-- author.html
|-- base.html
|-- category.html
|-- disqus.html
|-- footer.html
|-- header.html
|-- index.html
|-- page.html
|-- pagination.html
|-- post.html
`-- tag.html

**Comment by kracekumar** [comment]
I will look into it. Can you attach screenshot if you have modified/added
any new sections ?

On Tue, Feb 24, 2015 at 10:04 AM, shanki notifications@github.com wrote:

> I am maintaining 2 separate themes, one for frontend site(theme/site) and
> other for blog (theme/blog).
> - To modify templates related for frontend site such as index.html,
>   sponsorship.html etc. The modifications needs to be done on
>   theme/site/templates.
> 
> templates/
> |-- base.html
> |-- blogs.html
> |-- disqus.html
> |-- faq.html
> |-- footer.html
> |-- header.html
> |-- home.html
> |-- index.html
> |-- post.html
> |-- speakers.html
> |-- sponsorship.html
> |-- sponsors.html
> `-- venue.html
> - To modify templates related for blog site such as index.html etc.
>   The modifications needs to be done on theme/blog/templates.
> 
> templates/
> |-- analytics.html
> |-- archives.html
> |-- article.html
> |-- author.html
> |-- base.html
> |-- category.html
> |-- disqus.html
> |-- footer.html
> |-- header.html
> |-- index.html
> |-- page.html
> |-- pagination.html
> |-- post.html
> `-- tag.html
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pythonindia/inpycon2015/pull/4#issuecomment-75698117.

## 

Regards
Kracekumar Ramaraju
http://kracekumar.com
+91 85530 29521

**Comment by kracekumar** [comment]
@shankig Do you have sometime this weekend to rebase and fix merges ? If not let me know, I will take it up. Sorry for making this hang for long time.

**Comment by shankisg** [comment]
@kracekumar today night I will try to fix it else get back to you.

**Comment by kracekumar** [comment]
Thanks for the effort! We have dedicated blog repo https://github.com/pythonindia/inpycon-blog now. So closing this.

**Pull request closed without merging**
